import "dotenv/config"

export const ENV={
PORT:process.env.PORT,
NODE_ENV:process.env.NODE_ENV,
MONGO_URI:process.env.MONGO_URI,
JWT_SECRET:process.env.JWT_SECRET,
SMTP_USER:process.env.SMTP_USER,
SMTP_PASS:process.env.SMTP_PASS,
SMTP_MAIL:process.env.SMTP_MAIL,
CLIENT_URL:process.env.CLIENT_URL,
CLOUDINARY_CLOUD_NAME:process.env.CLOUDINARY_CLOUD_NAME,
CLOUDINARY_API_KEY:process.env.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET:process.env.CLOUDINARY_API_SECRET,
ARKJET_KEY:process.env.ARKJET_KEY,
ARKJET_ENV:process.env.ARKJET_ENV,
}